import '@/app/globals.css';
import Box from '@/components/Box';
import Search from '@/components/client/Search';
import SignInButton from '@/components/client/SignInButton';
import { applyMigrations } from '@/db/db';
import { CurrentPageParam } from '@/providers/CurrentPageParam';
import SessionProvider from '@/providers/SessionProvider';
import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import Link from 'next/link';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

const pokimonFont = localFont({
  src: '../../../public/fonts/Pokemon_Classic.ttf',
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  modal,
}: {
  children: ReactNode;
  modal: ReactNode;
}) {
  await applyMigrations();

  return (
    <html lang="en" className="min-h-screen">
      <body className={`${inter.className} ${pokimonFont.className}`}>
        <SessionProvider>
          <CurrentPageParam>
            <Box padded className="sticky top-1 z-40 m-1 mb-0">
              <nav className="flex items-center gap-4">
                <h1 className="shrink-0 text-4xl">
                  <Link href="/">Pokidex</Link>
                </h1>
                <div className="grow">
                  <Search />
                </div>
                <div className="shrink-0">
                  <SignInButton />
                </div>
              </nav>
            </Box>
            <main className="flex flex-col items-center justify-between gap-4 p-8">
              {children}
              {modal}
            </main>
          </CurrentPageParam>
        </SessionProvider>
      </body>
    </html>
  );
}
